### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kononnable** [Kononnable/kafka-connector#1]
- [x] Create parser and generate models for kafka communication
- [x] Automated tests
- [x] CI infrastructure
- [ ] Proper error handling(+ remove as many unwraps as reasonable)
- [ ] Producer
- [ ] Consumer
- [ ] Admin
- [ ] Support for some connection level options(based on https://kafka.apache.org/documentation.html#producerconfigs) + proper default values
- [ ] Support for record set compression
- [ ] Transactions
- [ ] Allow sending multiple requests in parallel(proper setting/checking last_correlation)
Quality of code:
- [ ] Limit amount of data copies(to_owned, clone)
- [x] Reuse structures not changed in previous api versions
- [ ] Reexport some types
- [ ] Introduce feature flags to limit compilation times
- [ ] Proper documentation
Later on:
- [ ] Ability to use different async runtimes
- [ ] SSL connection(openssl, rustls)
- [ ] SASL support
- [ ] Metrics
Maybe:
- [ ] Support kafka <0.11 - different record set format
- [ ] Support kafka <0.10 - no api versions api method
- [ ] Tagged field support
